---
title: "project"
author: "Peimin Lin"
date: "20/10/2020"
output: html_document
---

```{r setup}
library(tidyverse)
library(rpart)
library(MASS)
library(broom)
library(ggResidpanel)
library(fmsb)
library(dplyr)
library(gapminder)
library(ggplot2)
library(magrittr)
library(sf)
library(maps)
library(rnaturalearth)
library(leaflet)
library(RColorBrewer)
library(ggiraph)
hotel <- read_csv("Data/tidy.csv") %>% dplyr::select(-X1)
```

```{r select}
booking <- hotel %>% dplyr::select(lead_time,
                                 adr,
                                 is_canceled,
                                 reserved_room_type,
                                 assigned_room_type,
                                 arr_date_month, Country) %>%
  filter(is_canceled == 0) 
  # mutate( change = ifelse(!reserved_room_type == assigned_room_type, 1,0),
  #         reserved_room_type = case_when(reserved_room_type == "A" ~ 0,
  #                                        reserved_room_type == "B" ~ 1,
  #                                        reserved_room_type == "C" ~ 2,
  #                                        reserved_room_type == "D" ~ 3,
  #                                        reserved_room_type == "E" ~ 4,
  #                                        reserved_room_type == "F" ~ 5,
  #                                        reserved_room_type == "G" ~ 6,
  #                                        reserved_room_type == "H" ~ 7,
  #                                        reserved_room_type == "I" ~ 8),
  #        assigned_room_type = case_when(assigned_room_type == "A" ~ 0,
  #                                        assigned_room_type== "B" ~ 1,
  #                                        assigned_room_type == "C" ~ 2,
  #                                       assigned_room_type == "D" ~ 3,
  #                                        assigned_room_type == "E" ~ 4,
  #                                        assigned_room_type == "F" ~ 5,
  #                                        assigned_room_type == "G" ~ 6,
  #                                       assigned_room_type == "H" ~ 7,
  #                                        assigned_room_type == "I" ~ 8)
  #         )

```



```{r type}
type <- booking %>% 
   filter(!reserved_room_type == assigned_room_type) %>%
  group_by(lead_time, arr_date_month,reserved_room_type,assigned_room_type, Country) %>%
  count( name = "Number") 

```



```{r A}
A <- type %>% filter( arr_date_month == "10",
                      Country == "United Kingdom")
```


```{r ggplot}
leadplot <-ggplot(type, aes(x = factor(arr_date_month), y = lead_time, size = Number)) +
       geom_point(shape =21, colour = "#95CDF7", fill = "#F8BBD0") +    
     scale_x_discrete( name = "Month" ) +
     scale_y_continuous()
```




```{r coordplot}
polar <- ggplot(A, aes(x= reserved_room_type , y = log(Number*2), fill = assigned_room_type)) +
  geom_bar(stat = "identity", alpha = 0.7) +
 theme_minimal() +
  coord_polar() 
  

polar 
```






