---
title: "Expert advice from experts"
author:
- familyname: Curie
  othernames: Marie
  address: University of Paris
  email: mcurie.notreal@gmail.com
  correspondingauthor: true
  qualifications: Nobel Prize, PhD
- familyname: Curie
  othernames: Pierre
  address: University of Paris
  qualifications: Nobel Prize, PhD
department: Department of\newline Econometrics &\newline Business Statistics
organization: Acme Corporation
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  MonashEBSTemplates::report:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE)
# Make sure you have the latest versions of rmarkdown and bookdown installed
library(ggplot2)
library(tidyverse)
library(countrycode)
library(lubridate)
library(naniar)
hotels <- read.csv("data/hotels.csv")
```

```{r check NA}
Miss_tidy <- vis_miss(hotels, warn_large_data =FALSE) #check wether have mssing value in data set
Miss_tidy
```


```{r clean missing}
hotel <- na.omit(hotels)
```

```{r change_format}
hotel <- hotel %>% mutate(
    arr_date_month = case_when(   # change Month to the numeric 
    arrival_date_month=="January" ~ 01,
    arrival_date_month=="February" ~ 02,
    arrival_date_month=="March" ~ 03,
    arrival_date_month=="April" ~ 04,
    arrival_date_month=="May" ~ 05,
    arrival_date_month=="June" ~ 06,
    arrival_date_month=="July" ~ 07,
    arrival_date_month=="August" ~ 08,
    arrival_date_month=="September" ~ 09,
    arrival_date_month=="October" ~ 10,
    arrival_date_month=="November" ~ 11,
    arrival_date_month=="December" ~ 12),
    country = str_replace(country, pattern = "cn", replacement = "chn"), # replace China pattern
    deposit = case_when(deposit_type == "No Deposit"~0,            # Change deposit as binary numeric
                        deposit_type == "Non Refund"~1,
                         deposit_type == "Refundable"~2),
   arrival_time=paste(arrival_date_year,
                      arrival_date_month,
                      arrival_date_day_of_month,
                      sep="-"))%>%
   mutate(Country = countrycode(sourcevar = country,              # According the country code to find the country full name
                                      origin = "iso3c",
                                      destination = "country.name"),
          reservation_status_date=ymd(reservation_status_date),
         arrival_time=ymd(arrival_time)) 
```

```{r}
vis_tidy <- vis_miss(tidy, warn_large_data =FALSE)
vis_tidy
```



```{r tidy}
tidy <- hotel %>% dplyr::select(-market_segment,
                               -distribution_channel,
                               -deposit_type,
                               -agent,
                               -company) 
```


```{r}
final <- na.omit(tidy)  # Delete the missing country observations
  
```

1.Which day of the month is most common and which season (or month) has more customers in the whole year?


```{r}
library(plotly)
month_2016 <- tidy %>%
  filter(arrival_date_year == 2016) %>%
  group_by(arrival_date_day_of_month, arrival_date_month, hotel) %>%
  count(Count=n())

g1 <- ggplot(month_2016,
       aes(x=arrival_date_day_of_month, y=Count, color=arrival_date_month)) +
  xlab("Arrival day") +
  geom_col() + 
theme(axis.text.x = element_text()) 
  
ggplotly(g1)

```


```{r}
month_2016$arrival_date_month <- factor (month_2016$arrival_date_month,
                     levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"))
ggplot(month_2016,
       aes(x=arrival_date_month, y=Count, fill=hotel)) +
  geom_bar(stat = "identity", 
position = "stack") + 
  xlab("Month") +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

2.Comparing the most reserved season by different hotel types with different countries.

```{r}
library(kableExtra)
library(dplyr)
Top10Country <- tidy %>%
  count(Country, sort = T) %>%
  head(10) %>%
  kable(caption = "Top10 coutries reserved")
Top10Country
```


```{r}
month_countries <- tidy %>%
  filter(arrival_date_year == 2016,
         Country %in%c("Portugal", "United Kingdom", "Australia", "China")) %>%
  group_by(arrival_date_month, hotel, Country) %>%
  count(Count=n())
month_countries$arrival_date_month <- factor (month_countries$arrival_date_month,
                     levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"))
ggplot(month_countries,
       aes(x=arrival_date_month, y=Count, fill=hotel)) +
  geom_bar(stat = "identity", 
position = "stack") + 
  xlab("Month") +
  facet_wrap(~Country, scales = "free_y") +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


